### ISSUE TITLE
Barcodes Starting With Zero Not Matching

### ISSUE THREAD

**Issue by AdrienneRadzvickas** [CARLI/alma_inventory_docker#1]
1. We're currently running into errors when we try to load a batch of barcodes into the Alma Batch Inventory Report Tool-the tool can't seem to match them. A staff member reports that it worked in the recent past (earlier in January), but currently it seems to be unable to match many barcodes to items in our collection.

Many of Rush's barcodes begin with 0, so our initial guess was that the errors were caused by Excel treating the barcodes as numbers and dropping the initial 0s, but we've tried tweaking the formatting of the barcode column and can't seem to work around it. I've attached an input file (BD 444 D995 1993--BF 77 G947 2007.xlsx, generated in the Alma Interactive Inventory Scanning Tool and converted in Excel) and the resulting Alma Batch Inventory Report Tool report (rsh______ShelfList_MAIN_closed_bk___20230202.csv). Note that barcodes beginning with R (lines 300-320) were processed successfully.

**Comment by gibsonjc** [comment]
RT #129738

**Comment by cedelis** [comment]
This is an issue with Excel formatting where the barcodes are being treated as numbers (which causes the initial 0s to get dropped).

Here's a workaround:

1. convert the CSV file to an Excel Workbook:

- In Excel, open that original file that originated from the Interactive tool, then 'Save As' Excel Workbook (.xslx)

2. Notice how Excel interprets the barcode values as numbers

E.g., click on a random barcode value and notice how the cell contents are formatted like the following:

="0284807"

3. One way to workaround this issue is to change all of these barcode "number" values into "string" values.

Unfortunately, the intuitive method for doing this doesn't seem to work (i.e., selecting/highlighting the Barcode column, then performing a "Format / Cells...", then setting Format to "Text").

Instead, the following seems to work:

- select/highlight the Barcode column
- copy the column via "Edit / Copy" (or Ctrl-C)
- while column is still selected, click "Edit / Paste Special..."
- change the "Paste" option from "All" to "Values"
- click OK

Then, you will notice that the barcode formats have changed from:

="0284807"

to:

0284807

4. Save the changes to this Excel file

5. Re-load this Excel file into the Batch tool
